export const DetailConstants = {
    GET_DETAIL: 'GET_DETAIL',
    GET_DETAIL_RESPONSE: 'GET_DETAIL_RESPONSE',
    GET_DETAIL_ERROR: 'GET_DETAIL_ERROR',
    VIEW_DETAIL: 'VIEW_DETAIL',
    VIEW_ASIN: 'VIEW_ASIN',
};
