export const InventoryConstants = {
    GET_INVENTORY: 'GET_INVENTORY',
    GET_INVENTORY_RESPONSE: 'GET_INVENTORY_RESPONSE',
    GET_INVENTORY_ERROR: 'GET_INVENTORY_ERROR',
    VIEW_INVENTORY: 'VIEW_INVENTORY',
    GET_INVENTORY_SNAPSHOT_DATA: 'GET_INVENTORY_SNAPSHOT_DATA',
};
