export const PricingConstants = {
    GET_PRICING: 'GET_PRICING',
    GET_PRICING_RESPONSE: 'GET_PRICING_RESPONSE',
    GET_PRICING_ERROR: 'GET_PRICING_ERROR',
    GET_PRICING_SNAPSHOT_DATA: 'GET_PRICING_SNAPSHOT_DATA',
};
