export const TaskConstants = {
    GENERAL_REDIRECT: 'GENERAL_REDIRECT',
    PROFILE_REDIRECT: 'PROFILE_REDIRECT',
    ACCOUNT_REDIRECT: 'ACCOUNT_MANAGEMENT_REDIRECT',
    CREDENTIAL_REDIRECT: 'CREDENTIAL_REDIRECT',
    TAX_REDIRECT: 'TAX_REDIRECT',
    INLINE_TASK: 'INLINE_TASK',
    SNOOZE_ACTION: 'postpone',
    DISMISS_ACTION: 'dismiss',
    REDIRECT_ACTION: 'redirected',
    ACTION_ACTION: 'ACTION',
}
